export const GET_STICKYNOTES = "GET_STICKYNOTES";
export const ADD_STICKYNOTE = "ADD_STICKYNOTE";
export const DELETE_STICKYNOTE = "DELETE_STICKYNOTES";
export const STICKYNOTES_LOADING = "STICKYNOTES_LOADING";
